# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
"""The suite lock: does the ground under this run match the one the protocol froze?

A protocol that names a terrain suite by name alone does not lock the ground. The suite's content
and its seed live in ``suites.py``, and the mesh is generated by the engine, so two runs both saying
``lizard_suite_v2`` can stand on different terrain -- detectably, from the ``suite.digest`` and
``geometry_digest`` a record carries, but only *afterwards*. This module compares the expectation
before the measurement instead, in two steps because the two fingerprints become available at
different moments:

* ``cfg_digest`` -- the importer cfg the harness' own factory builds. Comparable before ``gym.make``,
  so a wrong suite is refused without paying for a simulator start.
* ``geometry_digest`` -- the generated ground, per cell. Only exists once the generator handed the
  meshes over, so it is compared after construction and before the rollout.

**Three outcomes, not two.** A geometry digest that differs while the *engine environment* also
differs is ``unknown``: terrain meshes come out of the engine, so a different PhysX build, GPU or
gpu compute capability is a second explanation for the same mismatch, and reporting it as "the
protocol changed" would blame the declaration for the machine. Only a digest mismatch inside the
frozen environment is a ``mismatch``.

Stdlib only, so this runs and is tested on a machine that cannot start the simulator.
"""

from __future__ import annotations

import json

#: Outcomes, ordered by how much the comparison proved.
MATCH = "match"
MISMATCH = "mismatch"
UNKNOWN = "unknown"
NOT_DECLARED = "not_declared"

#: The protocol version whose protocols must freeze their suite. Protocols published before it never
#: declared one, and a rule cannot retroactively require what was never asked for -- so they run
#: with the lock recorded as ``not_declared`` instead of being refused today.
FIRST_VERSION_REQUIRING_LOCK = 4

#: The fields ``geometry_env`` is judged on. Listed rather than compared wholesale: a field added to
#: the recorded environment must not silently turn every older declaration into an ``unknown``.
ENV_FIELDS = (
    "sim_version",
    "physx_version",
    "numpy_version",
    "warp_version",
    "torch_version",
    "gpu",
    "gpu_compute_capability",
    "git_rev_isaaclab",
)


def _bare(digest) -> str:
    """A digest without its algorithm prefix, for comparison.

    Two spellings of the same fact are in circulation: :func:`ablation_harness.record.digest` and
    the terrain probe return ``sha256:<hex>``, while ``cfg_snapshot.digest`` returns bare hex.
    Comparing the spelling instead of the digest makes a *correct* declaration read as a mismatch --
    which is exactly what this lock's first real run reported. The reported values stay as written,
    so a spelling difference is still visible whenever something else also differs.

    Caveat worth knowing: a value that is not a digest at all (a placeholder, a stray word) is
    compared verbatim, so it can only ever mismatch, never match.
    """
    text = str(digest)
    return text.split("sha256:", 1)[-1] if text.startswith("sha256:") else text


def fingerprint_verdict(declared: dict | None, key: str, actual, *, engine_bound: bool,
                        env: dict | None = None) -> dict:
    """Compare one frozen fingerprint with what this run produced.

    Args:
        declared: the protocol's ``suite_expected`` block, or ``None`` when it froze nothing.
        key: which fingerprint (``cfg_digest`` or ``geometry_digest``).
        actual: the value this run produced.
        engine_bound: whether the measured object is produced by the engine, and therefore whether
            an environment difference turns a mismatch into ``unknown``.
        env: the environment this run is in, for the ``engine_bound`` comparison.
    """
    result = {"verdict": NOT_DECLARED, "declared": None, "actual": actual}
    if declared is None or declared.get(key) is None:
        return result
    result["declared"] = declared[key]
    if _bare(declared[key]) == _bare(actual):
        return {**result, "verdict": MATCH}
    if engine_bound:
        want_env = declared.get("geometry_env") or {}
        if env is not None:
            moved = sorted(name for name in ENV_FIELDS
                           if name in want_env and env.get(name) != want_env[name])
            if moved:
                spelled = ", ".join(f"{name}: {want_env[name]} -> {env.get(name)}" for name in moved)
                return {**result, "verdict": UNKNOWN,
                        "reason": f"{key} differs and this is not the environment it was frozen in "
                                  f"({spelled})"}
    return {**result, "verdict": MISMATCH,
            "reason": f"{key} is {actual} but the protocol froze {declared[key]}"}


def compare(protocol: dict, cfg_digest: str, geometry_digest: str, env: dict) -> dict:
    """Both fingerprints against the protocol's declaration, plus the environment they were read in."""
    declared = protocol.get("suite_expected")
    cfg = fingerprint_verdict(declared, "cfg_digest", cfg_digest, engine_bound=False)
    geometry = fingerprint_verdict(declared, "geometry_digest", geometry_digest,
                                  engine_bound=True, env=env)
    states = (cfg["verdict"], geometry["verdict"])
    if MISMATCH in states:
        verdict = MISMATCH
    elif UNKNOWN in states:
        verdict = UNKNOWN
    elif NOT_DECLARED in states:
        verdict = NOT_DECLARED
    else:
        verdict = MATCH
    return {"verdict": verdict, "declared": declared, "geometry_env": env,
            "cfg": cfg, "geometry": geometry}


def start_refusal(protocol: dict, lock: dict, *, stage: str) -> str | None:
    """Why this run must not start, or ``None``.

    Only the stage being checked can refuse, because only that stage's fingerprint exists at that
    moment: the cfg is comparable before the env is built, the geometry is not. "This protocol
    freezes nothing" is therefore answered at the geometry stage -- which is also the stage the
    fingerprint-printing path answers it from, so the two cannot deadlock.
    """
    if lock[stage]["verdict"] == MISMATCH:
        return lock[stage]["reason"]
    if (stage == "geometry" and lock["verdict"] == NOT_DECLARED
            and int(protocol.get("version") or 0) >= FIRST_VERSION_REQUIRING_LOCK):
        return (f"{protocol.get('name')} freezes no suite fingerprint, so this run could not be "
                f"attributed to a ground. Run with --print-suite-fingerprint once, paste the block "
                f"it prints into the protocol's suite_expected, and then this check is enforced")
    return None


def fingerprint_block(protocol: dict, cfg_digest: str, geometry_digest: str, env: dict) -> str:
    """The ``suite_expected`` block to paste, as JSON (approving one is a deliberate act)."""
    return json.dumps({
        "name": protocol.get("suite"),
        "cfg_digest": cfg_digest,
        "geometry_digest": geometry_digest,
        "geometry_env": env,
    }, indent=2, ensure_ascii=False)
