@echo off
setlocal EnableDelayedExpansion
rem ---------------------------------------------------------------------------
rem One-shot machine placement for this repo: the five steps README's
rem "huan jing yao qiu" section spells out by hand, plus the fork patches.
rem
rem   setup.bat ROOT [VENV_DIR]
rem     ROOT      IsaacLab SOURCE tree (the one holding source\isaaclab,
rem               scripts\ and logs\ -- NOT this repo)
rem     VENV_DIR  venv inside it; default ROOT\env_isaaclab
rem
rem Idempotent: re-run after a git pull (fork patches already in the tree are
rem skipped) or after a ROOT reinstall. Writes only: the venv .pth, the
rem task-registration shim, the patches it can apply, and paths.yaml here.
rem
rem ASCII ONLY on purpose -- a .bat is read with the console codepage, so
rem non-ASCII comments get mangled and the parser derails. Keep it that way.
rem
rem Success is checked by OUTCOME (file exists / git exit code), never by a
rem leftover ERRORLEVEL: echo and a successful redirection leave it untouched,
rem so "if errorlevel 1" here would inherit whatever failed before.
rem ---------------------------------------------------------------------------

set "REPO=%~dp0"
if "%REPO:~-1%"=="\" set "REPO=%REPO:~0,-1%"

if "%~1"=="" goto :usage
set "ROOT=%~1"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
set "VENV=%~2"
if "%VENV%"=="" set "VENV=%ROOT%\env_isaaclab"
if not "%VENV%"=="" if "%VENV:~-1%"=="\" set "VENV=%VENV:~0,-1%"

set "RC=0"
echo REPO = %REPO%
echo ROOT = %ROOT%
echo VENV = %VENV%
echo.

rem --- preflight: fail before touching anything -------------------------------
if not exist "%ROOT%\source\isaaclab" (
    echo [FAIL] %ROOT%\source\isaaclab not found -- not an IsaacLab source tree.
    exit /b 1
)
if not exist "%ROOT%\.git" (
    echo [FAIL] %ROOT%\.git not found -- the fork patches need a git checkout of the tree.
    exit /b 1
)
if not exist "%VENV%\Scripts\python.exe" (
    echo [FAIL] %VENV%\Scripts\python.exe not found -- pass VENV_DIR as the 2nd argument.
    exit /b 1
)

rem --- 1. venv .pth: makes the rl_exp package importable from anywhere --------
set "PTH=%VENV%\Lib\site-packages\rl_exp.pth"
> "%PTH%" echo %REPO%
if exist "%PTH%" (echo [ok]   1. rl_exp.pth written: %PTH%) else (echo [FAIL] 1. could not write %PTH% & set "RC=1")

rem --- 2. fork shim: importing isaaclab_tasks registers every lizard task ----
rem import_packages walks the tree with pkgutil and imports every directory
rem holding an __init__.py, so dropping the file in is enough -- but the
rem "lizard" directory does not exist in a stock tree, hence the mkdir.
set "SHIM_DIR=%ROOT%\source\isaaclab_tasks\isaaclab_tasks\manager_based\locomotion\velocity\config\lizard"
if not exist "%SHIM_DIR%" mkdir "%SHIM_DIR%"
copy /y "%REPO%\rl_exp\fork_patches\config_lizard___init__.py" "%SHIM_DIR%\__init__.py" >nul
if exist "%SHIM_DIR%\__init__.py" (echo [ok]   2. fork shim written: %SHIM_DIR%\__init__.py) else (echo [FAIL] 2. could not copy the shim into %SHIM_DIR% & set "RC=1")

rem --- 3. fork patches: skip what is already applied, report every decision --
rem "apply --check --reverse" succeeds exactly when the patch is already in the
rem tree, so a forgotten patch shows up here instead of silently doing nothing
rem later. git sets ERRORLEVEL on the line right before each test, so it is
rem fresh here (unlike the outcome checks above).
for %%p in ("%REPO%\rl_exp\fork_patches\*.patch") do (
    if exist "%%~fp" (
        git -C "%ROOT%" apply --check --reverse "%%~fp" >nul 2>&1
        if !errorlevel! equ 0 (
            echo [ok]   3. %%~nxp already applied - skipped
        ) else (
            git -C "%ROOT%" apply "%%~fp" >nul 2>&1
            if !errorlevel! equ 0 (
                echo [ok]   3. %%~nxp applied
            ) else (
                echo [FAIL] 3. %%~nxp neither applied nor appliable -- fix it or re-pin
                set "RC=1"
            )
        )
    )
)

rem --- 4. machine-local host paths (the SSOT host_paths.py reads) -------------
if exist "%REPO%\paths.yaml" (
    echo [ok]   4. paths.yaml already present - left alone ^(delete to regenerate^)
) else (
    set "ROOT_FWD=%ROOT:\=/%"
    set "PY_FWD=%VENV:\=/%/Scripts/python.exe"
    (
        echo # Machine-local host paths. Contract + field docs: paths.example.yaml.
        echo # Generated by setup.bat; ablation_harness/host_paths.py is the only reader.
        echo isaac_root: !ROOT_FWD!
        echo python: !PY_FWD!
    ) > "%REPO%\paths.yaml"
    if exist "%REPO%\paths.yaml" (echo [ok]   4. paths.yaml written for this machine) else (echo [FAIL] 4. could not write paths.yaml & set "RC=1")
)

rem --- 5. pre-commit gate (local git config, does not travel with the repo) --
git -C "%REPO%" config core.hooksPath hooks
if !errorlevel! equ 0 (echo [ok]   5. core.hooksPath -^> hooks) else (echo [FAIL] 5. could not set core.hooksPath & set "RC=1")

echo.
if not "%RC%"=="0" (
    echo SETUP_FAILED -- fix the [FAIL] lines above and re-run.
    exit /b 1
)
echo SETUP_OK -- now run the verification chain:
echo   cd /d %REPO%
echo   "%VENV%\Scripts\python.exe" ablation_harness\host_paths.py --check
echo   rl_exp\tools\verify\run_offline_checks.bat
echo   "%VENV%\Scripts\python.exe" rl_exp\tools\verify\teacher_smoke.py --headless
exit /b 0

:usage
echo Usage: setup.bat ROOT [VENV_DIR]
echo   ROOT      IsaacLab SOURCE tree (holds source\isaaclab, scripts\, logs\)
echo   VENV_DIR  venv inside it; default ROOT\env_isaaclab
echo.
echo Example: setup.bat E:\IsaacLab
exit /b 1
